import {
  BitgetWalletAdapter,
  BitKeepWalletAdapter,
  BitpieWalletAdapter,
  CloverWalletAdapter,
  Coin98WalletAdapter,
  CoinbaseWalletAdapter,
  CoinhubWalletAdapter,
  HuobiWalletAdapter,
  KrystalWalletAdapter,
  LedgerWalletAdapter,
  MathWalletAdapter,
  NightlyWalletAdapter,
  PhantomWalletAdapter,
  SaifuWalletAdapter,
  SkyWalletAdapter,
  SolflareWalletAdapter,
  SpotWalletAdapter,
  TokenaryWalletAdapter,
  TokenPocketWalletAdapter,
  TorusWalletAdapter,
  TrustWalletAdapter,
  XDEFIWalletAdapter,
} from "@solana/wallet-adapter-wallets";

// Create wallet adapters - using only available adapters
const wallets = [
  new PhantomWalletAdapter(),
  new SolflareWalletAdapter(),
  new BitgetWalletAdapter(),
  new TorusWalletAdapter(),
  new LedgerWalletAdapter(),
  new MathWalletAdapter(),
  new CoinbaseWalletAdapter(),
  new BitpieWalletAdapter(),
  new BitKeepWalletAdapter(),
  new CloverWalletAdapter(),
  new Coin98WalletAdapter(),
  new CoinhubWalletAdapter(),
  new HuobiWalletAdapter(),
  new KrystalWalletAdapter(),
  new NightlyWalletAdapter(),
  new SaifuWalletAdapter(),
  new SkyWalletAdapter(),
  new SpotWalletAdapter(),
  new TokenPocketWalletAdapter(),
  new TokenaryWalletAdapter(),
  new TrustWalletAdapter(),
  new XDEFIWalletAdapter(),
];

export default wallets;
