export const ID_MARKET_HOTSPOTS = {
    VENDOR: "ID_MARKET_HOTSPOTS_VENDOR",
    SAGE: "ID_MARKET_HOTSPOTS_SAGE",
    DEX: "ID_MARKET_HOTSPOTS_DEX",
    BANKER: "ID_MARKET_HOTSPOTS_BANKER",
    HELPER: "ID_MARKET_HOTSPOTS_HELPER",
    MARKET: "ID_MARKET_HOTSPOTS_MARKET",
    LEADERBOARD: "ID_MARKET_HOTSPOTS_LEADERBOARD",
}

export const ID_SEED_SHOP_ITEMS = {
    FEEBLE_SEED: "ID_SEED_SHOP_ITEM_FEEBLE_SEED",
    PICO_SEED: "ID_SEED_SHOP_ITEM_PICO_SEED",
    BASIC_SEED: "ID_SEED_SHOP_ITEM_BASIC_SEED",
    PREMIUM_SEED: "ID_SEED_SHOP_ITEM_PREMIUM_SEED",
}